
//! Autogenerated weights for `pallet_alpha_bridge`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.1
//! DATE: 2025-10-23, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Ubuntu-2404-noble-amd64-base`, CPU: `Intel(R) Xeon(R) CPU E3-1275 v5 @ 3.60GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/hippius
// benchmark
// pallet
// --runtime=./target/release/wbuild/hippius-mainnet-runtime/hippius_mainnet_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet=pallet_alpha_bridge
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template=pallets/benchmarking/frame-weight-template.hbs
// --output=pallets/alpha-bridge/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_alpha_bridge`.
pub trait WeightInfo {
	fn withdraw() -> Weight;
	fn attest_deposit() -> Weight;
	fn cleanup_deposit() -> Weight;
	fn cleanup_withdrawal_request() -> Weight;
	fn set_guardians_and_threshold(g: u32) -> Weight;
	fn pause() -> Weight;
	fn unpause() -> Weight;
	fn set_global_mint_cap() -> Weight;
	fn set_cleanup_ttl() -> Weight;
	fn set_min_withdrawal_amount() -> Weight;
	fn admin_cancel_deposit() -> Weight;
	fn admin_fail_withdrawal_request() -> Weight;
	fn admin_manual_mint() -> Weight;
}

/// Weights for `pallet_alpha_bridge` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `AlphaBridge::Paused` (r:1 w:0)
	/// Proof: `AlphaBridge::Paused` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::MinWithdrawalAmount` (r:1 w:0)
	/// Proof: `AlphaBridge::MinWithdrawalAmount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::TotalMintedByBridge` (r:1 w:1)
	/// Proof: `AlphaBridge::TotalMintedByBridge` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::NextWithdrawalRequestNonce` (r:1 w:1)
	/// Proof: `AlphaBridge::NextWithdrawalRequestNonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AlphaBridge::WithdrawalRequests` (r:0 w:1)
	/// Proof: `AlphaBridge::WithdrawalRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn withdraw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `94`
		//  Estimated: `6196`
		// Minimum execution time: 68_533_000 picoseconds.
		Weight::from_parts(69_357_000, 6196)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `AlphaBridge::Guardians` (r:1 w:0)
	/// Proof: `AlphaBridge::Guardians` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::Paused` (r:1 w:0)
	/// Proof: `AlphaBridge::Paused` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::Deposits` (r:1 w:1)
	/// Proof: `AlphaBridge::Deposits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::ApproveThreshold` (r:1 w:0)
	/// Proof: `AlphaBridge::ApproveThreshold` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::TotalMintedByBridge` (r:1 w:1)
	/// Proof: `AlphaBridge::TotalMintedByBridge` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::GlobalMintCap` (r:1 w:0)
	/// Proof: `AlphaBridge::GlobalMintCap` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn attest_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `454`
		//  Estimated: `3919`
		// Minimum execution time: 61_580_000 picoseconds.
		Weight::from_parts(61_580_000, 3919)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `AlphaBridge::Guardians` (r:1 w:0)
	/// Proof: `AlphaBridge::Guardians` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::Deposits` (r:1 w:1)
	/// Proof: `AlphaBridge::Deposits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::CleanupTTLBlocks` (r:1 w:0)
	/// Proof: `AlphaBridge::CleanupTTLBlocks` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn cleanup_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `180`
		//  Estimated: `3645`
		// Minimum execution time: 22_285_000 picoseconds.
		Weight::from_parts(22_285_000, 3645)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AlphaBridge::Guardians` (r:1 w:0)
	/// Proof: `AlphaBridge::Guardians` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::WithdrawalRequests` (r:1 w:1)
	/// Proof: `AlphaBridge::WithdrawalRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::CleanupTTLBlocks` (r:1 w:0)
	/// Proof: `AlphaBridge::CleanupTTLBlocks` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn cleanup_withdrawal_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `180`
		//  Estimated: `3645`
		// Minimum execution time: 22_285_000 picoseconds.
		Weight::from_parts(22_285_000, 3645)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AlphaBridge::Guardians` (r:0 w:1)
	/// Proof: `AlphaBridge::Guardians` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::ApproveThreshold` (r:0 w:1)
	/// Proof: `AlphaBridge::ApproveThreshold` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `g` is `[1, 10]`.
	fn set_guardians_and_threshold(g: u32, ) -> Weight {
		Weight::from_parts(14_725_697, 1542)
			.saturating_add(Weight::from_parts(33_949, 0).saturating_mul(g.into()))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(g.into()))
	}
	/// Storage: `AlphaBridge::Paused` (r:0 w:1)
	/// Proof: `AlphaBridge::Paused` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn pause() -> Weight {
		Weight::from_parts(7_881_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AlphaBridge::Paused` (r:0 w:1)
	/// Proof: `AlphaBridge::Paused` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn unpause() -> Weight {
		Weight::from_parts(7_881_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AlphaBridge::TotalMintedByBridge` (r:1 w:0)
	/// Proof: `AlphaBridge::TotalMintedByBridge` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::GlobalMintCap` (r:0 w:1)
	/// Proof: `AlphaBridge::GlobalMintCap` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_global_mint_cap() -> Weight {
		Weight::from_parts(10_090_000, 1505)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AlphaBridge::CleanupTTLBlocks` (r:1 w:1)
	/// Proof: `AlphaBridge::CleanupTTLBlocks` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_cleanup_ttl() -> Weight {
		Weight::from_parts(10_090_000, 1505)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AlphaBridge::MinWithdrawalAmount` (r:1 w:1)
	/// Proof: `AlphaBridge::MinWithdrawalAmount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_min_withdrawal_amount() -> Weight {
		Weight::from_parts(10_090_000, 1505)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AlphaBridge::Deposits` (r:1 w:1)
	/// Proof: `AlphaBridge::Deposits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn admin_cancel_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `180`
		//  Estimated: `3645`
		// Minimum execution time: 22_285_000 picoseconds.
		Weight::from_parts(22_285_000, 3645)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AlphaBridge::WithdrawalRequests` (r:1 w:1)
	/// Proof: `AlphaBridge::WithdrawalRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::TotalMintedByBridge` (r:1 w:1)
	/// Proof: `AlphaBridge::TotalMintedByBridge` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::GlobalMintCap` (r:1 w:0)
	/// Proof: `AlphaBridge::GlobalMintCap` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn admin_fail_withdrawal_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `454`
		//  Estimated: `6196`
		// Minimum execution time: 78_617_000 picoseconds.
		Weight::from_parts(78_617_000, 6196)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `AlphaBridge::TotalMintedByBridge` (r:1 w:1)
	/// Proof: `AlphaBridge::TotalMintedByBridge` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::GlobalMintCap` (r:1 w:0)
	/// Proof: `AlphaBridge::GlobalMintCap` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn admin_manual_mint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `94`
		//  Estimated: `3559`
		// Minimum execution time: 30_000_000 picoseconds.
		Weight::from_parts(30_000_000, 3559)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `AlphaBridge::Paused` (r:1 w:0)
	/// Proof: `AlphaBridge::Paused` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::MinWithdrawalAmount` (r:1 w:0)
	/// Proof: `AlphaBridge::MinWithdrawalAmount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::TotalMintedByBridge` (r:1 w:1)
	/// Proof: `AlphaBridge::TotalMintedByBridge` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::NextWithdrawalRequestNonce` (r:1 w:1)
	/// Proof: `AlphaBridge::NextWithdrawalRequestNonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AlphaBridge::WithdrawalRequests` (r:0 w:1)
	/// Proof: `AlphaBridge::WithdrawalRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn withdraw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `94`
		//  Estimated: `6196`
		// Minimum execution time: 68_533_000 picoseconds.
		Weight::from_parts(69_357_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `AlphaBridge::Guardians` (r:1 w:0)
	/// Proof: `AlphaBridge::Guardians` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::Paused` (r:1 w:0)
	/// Proof: `AlphaBridge::Paused` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::Deposits` (r:1 w:1)
	/// Proof: `AlphaBridge::Deposits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::ApproveThreshold` (r:1 w:0)
	/// Proof: `AlphaBridge::ApproveThreshold` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::TotalMintedByBridge` (r:1 w:1)
	/// Proof: `AlphaBridge::TotalMintedByBridge` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::GlobalMintCap` (r:1 w:0)
	/// Proof: `AlphaBridge::GlobalMintCap` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn attest_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `454`
		//  Estimated: `3919`
		// Minimum execution time: 61_580_000 picoseconds.
		Weight::from_parts(61_580_000, 3919)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `AlphaBridge::Guardians` (r:1 w:0)
	/// Proof: `AlphaBridge::Guardians` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::Deposits` (r:1 w:1)
	/// Proof: `AlphaBridge::Deposits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::CleanupTTLBlocks` (r:1 w:0)
	/// Proof: `AlphaBridge::CleanupTTLBlocks` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn cleanup_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `180`
		//  Estimated: `3645`
		// Minimum execution time: 22_285_000 picoseconds.
		Weight::from_parts(22_285_000, 3645)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AlphaBridge::Guardians` (r:1 w:0)
	/// Proof: `AlphaBridge::Guardians` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::WithdrawalRequests` (r:1 w:1)
	/// Proof: `AlphaBridge::WithdrawalRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::CleanupTTLBlocks` (r:1 w:0)
	/// Proof: `AlphaBridge::CleanupTTLBlocks` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn cleanup_withdrawal_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `180`
		//  Estimated: `3645`
		// Minimum execution time: 22_285_000 picoseconds.
		Weight::from_parts(22_285_000, 3645)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AlphaBridge::Guardians` (r:0 w:1)
	/// Proof: `AlphaBridge::Guardians` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::ApproveThreshold` (r:0 w:1)
	/// Proof: `AlphaBridge::ApproveThreshold` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `g` is `[1, 10]`.
	fn set_guardians_and_threshold(g: u32, ) -> Weight {
		Weight::from_parts(14_725_697, 1542)
			.saturating_add(Weight::from_parts(33_949, 0).saturating_mul(g.into()))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(g.into()))
	}
	/// Storage: `AlphaBridge::Paused` (r:0 w:1)
	/// Proof: `AlphaBridge::Paused` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn pause() -> Weight {
		Weight::from_parts(7_881_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AlphaBridge::Paused` (r:0 w:1)
	/// Proof: `AlphaBridge::Paused` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn unpause() -> Weight {
		Weight::from_parts(7_881_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AlphaBridge::TotalMintedByBridge` (r:1 w:0)
	/// Proof: `AlphaBridge::TotalMintedByBridge` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::GlobalMintCap` (r:0 w:1)
	/// Proof: `AlphaBridge::GlobalMintCap` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_global_mint_cap() -> Weight {
		Weight::from_parts(10_090_000, 1505)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AlphaBridge::CleanupTTLBlocks` (r:1 w:1)
	/// Proof: `AlphaBridge::CleanupTTLBlocks` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_cleanup_ttl() -> Weight {
		Weight::from_parts(10_090_000, 1505)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AlphaBridge::MinWithdrawalAmount` (r:1 w:1)
	/// Proof: `AlphaBridge::MinWithdrawalAmount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_min_withdrawal_amount() -> Weight {
		Weight::from_parts(10_090_000, 1505)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AlphaBridge::Deposits` (r:1 w:1)
	/// Proof: `AlphaBridge::Deposits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn admin_cancel_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `180`
		//  Estimated: `3645`
		// Minimum execution time: 22_285_000 picoseconds.
		Weight::from_parts(22_285_000, 3645)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AlphaBridge::WithdrawalRequests` (r:1 w:1)
	/// Proof: `AlphaBridge::WithdrawalRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::TotalMintedByBridge` (r:1 w:1)
	/// Proof: `AlphaBridge::TotalMintedByBridge` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::GlobalMintCap` (r:1 w:0)
	/// Proof: `AlphaBridge::GlobalMintCap` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn admin_fail_withdrawal_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `454`
		//  Estimated: `6196`
		// Minimum execution time: 78_617_000 picoseconds.
		Weight::from_parts(78_617_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `AlphaBridge::TotalMintedByBridge` (r:1 w:1)
	/// Proof: `AlphaBridge::TotalMintedByBridge` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AlphaBridge::GlobalMintCap` (r:1 w:0)
	/// Proof: `AlphaBridge::GlobalMintCap` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn admin_manual_mint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `94`
		//  Estimated: `3559`
		// Minimum execution time: 30_000_000 picoseconds.
		Weight::from_parts(30_000_000, 3559)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
