//! Autogenerated weights for `pallet_compute_scoring` (PR-I4 slim).
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI
//! VERSION 4.0.0 (manual estimation as baseline — run actual
//! benchmarks in your runtime before mainnet).
//!
//! PR-I4 trimmed the upstream arion-pallet weight table down to only
//! the extrinsics still exposed by the simplified pallet (CRUSH /
//! warden / file-size / node-quality methods all dropped). See
//! `CHANGES.md` PR-I4 for the rip.

#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::traits::Get;
use frame_support::weights::{constants::RocksDbWeight, Weight};
use sp_std::marker::PhantomData;

/// Weight functions needed for `pallet_compute_scoring` (post-PR-I4).
pub trait WeightInfo {
    // --- §13 anti-Sybil registration ---
    fn register_child() -> Weight;
    fn deregister_child() -> Weight;
    fn claim_unbonded() -> Weight;
    fn request_unstake() -> Weight;

    // --- Admin ---
    fn set_vali_submitter() -> Weight;
    fn set_lockup_enabled() -> Weight;
    fn set_base_child_deposit() -> Weight;
    fn set_free_child_slots_per_family() -> Weight;

    // --- PR-I3 audit-stats ---
    fn submit_audit_stats() -> Weight;
    fn set_audit_vm_pubkey() -> Weight;

    // --- PR-I4 epoch close ---
    /// `n` = status updates in the batch; `p` =
    /// `Config::MaxEpochPruneKeysPerCall`, the R27 history sweep's
    /// per-call key budget.
    fn vali_submit_epoch_close(n: u32, p: u32) -> Weight;

    // --- #322 live attestation ---
    fn set_kbs_attestation_pubkey() -> Weight;
    fn remove_kbs_attestation_pubkey() -> Weight;
    fn submit_live_attestation() -> Weight;
}

/// Weights for `pallet_compute_scoring` using the Substrate node and
/// recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: 4 reads (registration tables) + ~6 writes (insert + counters).
    fn register_child() -> Weight {
        Weight::from_parts(35_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(8))
            .saturating_add(T::DbWeight::get().writes(8))
    }

    /// Storage: ~6 reads + ~6 writes (status flip + counter updates).
    fn deregister_child() -> Weight {
        Weight::from_parts(30_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(6))
    }

    fn claim_unbonded() -> Weight {
        Weight::from_parts(20_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    /// Gap #2 graceful-exit quarantine. Base unbond cost is 3 reads
    /// (`StakedAmount`, `StakeUnbonding`, `StakeEnabled`/`StakeFloor`) and 2
    /// writes (`StakedAmount`, `StakeUnbonding`). On the exit path it adds an
    /// O(children) loop bounded by `MaxChildrenPerFamily`, where each child
    /// costs 1 read (`ChildRegistrations`) plus the worst-case status
    /// transition (1 read and 1 write of `MinerStatuses`) — modelled here at
    /// the conservative upper bound `MAX_CHILDREN` so the table needs no `n`
    /// argument. Re-bench in the runtime before mainnet (manual estimate).
    fn request_unstake() -> Weight {
        // Conservative bound on `MaxChildrenPerFamily`; the production
        // runtime sets the real value, the actual loop is `saturating`-safe.
        const MAX_CHILDREN: u64 = 64;
        Weight::from_parts(20_000_000, 0)
            .saturating_add(Weight::from_parts(2_000_000, 0).saturating_mul(MAX_CHILDREN))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().reads(2u64.saturating_mul(MAX_CHILDREN)))
            .saturating_add(T::DbWeight::get().writes(2))
            .saturating_add(T::DbWeight::get().writes(MAX_CHILDREN))
    }

    fn set_vali_submitter() -> Weight {
        Weight::from_parts(5_000_000, 0).saturating_add(T::DbWeight::get().writes(1))
    }

    fn set_lockup_enabled() -> Weight {
        Weight::from_parts(5_000_000, 0).saturating_add(T::DbWeight::get().writes(1))
    }

    fn set_base_child_deposit() -> Weight {
        Weight::from_parts(5_000_000, 0).saturating_add(T::DbWeight::get().writes(1))
    }

    fn set_free_child_slots_per_family() -> Weight {
        Weight::from_parts(5_000_000, 0).saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: 5 reads (chain_genesis / pallet_instance / epoch /
    ///   prev_hash / pubkey) + 2 writes (LastAggregateHashByNode +
    ///   event); ed25519 verify dominates the runtime cost.
    fn submit_audit_stats() -> Weight {
        Weight::from_parts(80_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    fn set_audit_vm_pubkey() -> Weight {
        Weight::from_parts(5_000_000, 0).saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: 1 read (CurrentEpoch) + `n` × (1 read + 2 writes)
    ///   for `EpochWeights` insert + `MinerStatuses` read/insert,
    ///   plus a final write for `CurrentEpoch` + `EpochClosed`
    ///   event deposit. Snapshot collection for `RankingsSink` is
    ///   done in-memory (O(n) CPU). Dedupe uses a `BTreeSet`:
    ///   O(n log n) — the per-element coefficient below absorbs
    ///   the worst-case log-factor at typical bounds (≤ 256).
    ///   The R27 history sweep at the end of the call is charged
    ///   separately via `p` — see below.
    fn vali_submit_epoch_close(n: u32, p: u32) -> Weight {
        // Per-element cost (4_500_000 ps) is set higher than a
        // pure linear cost to absorb the O(n log n) dedupe inside
        // the BTreeSet — at n = 256, log2(n) ≈ 8, so a 4.5x base
        // per element is conservative.
        //
        // The `p` term prices the R27 sweep, which previously cost
        // NOTHING here while deleting up to ~12 k keys
        // (thebrain#49 re-review). `Pallet::sweep_epoch_history` is
        // bounded by construction at `p + 1` deletions and at most
        // `p` loop iterations, each iteration probing two prefixes
        // — so 2p reads and p+1 writes is a true upper bound, and
        // the epoch-jump case (a long run of empty epochs) is
        // covered by the same bound because each empty epoch still
        // costs one budget unit.
        Weight::from_parts(20_000_000, 0)
            .saturating_add(Weight::from_parts(4_500_000, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().reads(n.into()))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(T::DbWeight::get().writes((2u64).saturating_mul(n.into())))
            // R27 sweep: watermark + retention reads, watermark write.
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(T::DbWeight::get().reads((2u64).saturating_mul(p.into())))
            .saturating_add(T::DbWeight::get().writes((p as u64).saturating_add(1)))
    }

    fn set_kbs_attestation_pubkey() -> Weight {
        Weight::from_parts(5_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn remove_kbs_attestation_pubkey() -> Weight {
        Weight::from_parts(5_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: 5 reads (chain_genesis / pallet_instance / epoch /
    ///   LastLiveAttestation / KbsAttestationPubkeys) + 3 writes
    ///   (LastLiveAttestation + LiveAttestationCount + event);
    ///   Ed25519 verify dominates the runtime cost (same model as
    ///   `submit_audit_stats`).
    fn submit_live_attestation() -> Weight {
        Weight::from_parts(80_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(3))
    }
}

/// `()` impl for runtimes / tests that don't care about precise
/// weight benchmarks (zero weight; do NOT use in production).
impl WeightInfo for () {
    fn register_child() -> Weight {
        Weight::zero()
    }
    fn deregister_child() -> Weight {
        Weight::zero()
    }
    fn claim_unbonded() -> Weight {
        Weight::zero()
    }
    fn request_unstake() -> Weight {
        Weight::zero()
    }
    fn set_vali_submitter() -> Weight {
        Weight::zero()
    }
    fn set_lockup_enabled() -> Weight {
        Weight::zero()
    }
    fn set_base_child_deposit() -> Weight {
        Weight::zero()
    }
    fn set_free_child_slots_per_family() -> Weight {
        Weight::zero()
    }
    fn submit_audit_stats() -> Weight {
        Weight::zero()
    }
    fn set_audit_vm_pubkey() -> Weight {
        Weight::zero()
    }
    fn vali_submit_epoch_close(_n: u32, _p: u32) -> Weight {
        Weight::zero()
    }
    fn set_kbs_attestation_pubkey() -> Weight {
        Weight::zero()
    }
    fn remove_kbs_attestation_pubkey() -> Weight {
        Weight::zero()
    }
    fn submit_live_attestation() -> Weight {
        Weight::zero()
    }
}
