[package]
name = "pallet-arion"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
frame-support = { workspace = true, default-features = false }
frame-system  = { workspace = true, default-features = false }
frame-benchmarking = { workspace = true, default-features = false, optional = true }
sp-runtime    = { workspace = true, default-features = false }
sp-std        = { workspace = true, default-features = false }
sp-core       = { workspace = true, default-features = false }
sp-staking    = { workspace = true, default-features = false }
log           = { version = "0.4.22", default-features = false }
pallet-registration = { workspace = true, default-features = false }
pallet-proxy = { workspace = true, default-features = false }
payment-math = { workspace = true }

codec = { package = "parity-scale-codec", workspace = true, default-features = false, features = ["derive"] }
scale-info = { workspace = true, default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = [
  "frame-support/std",
  "frame-system/std",
  "frame-benchmarking?/std",
  "sp-runtime/std",
  "sp-std/std",
  "sp-core/std",
  "sp-staking/std",
  "pallet-registration/std",
  "pallet-proxy/std",
  "payment-math/std",
  "codec/std",
  "scale-info/std",
  "log/std",
]
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
  "sp-staking/runtime-benchmarks",
  "pallet-registration/runtime-benchmarks",
  "pallet-proxy/runtime-benchmarks",
]
try-runtime = [
  "frame-support/try-runtime",
  "frame-system/try-runtime",
]